[[protocols]]
name = "Mecool KII"
protocol = "nec"
[protocols.scancodes]
0x19 = "KEY_MUTE"
0x17 = "KEY_VOLUMEDOWN"
0x13 = "KEY_VOLUMEUP"
0x0d = "KEY_HOME"
0x11 = "KEY_DVD"
0x42 = "KEY_RED"
0x40 = "KEY_GREEN"
0x00 = "KEY_YELLOW"
0x03 = "KEY_BLUE"
0x5a = "KEY_LEFT"
0x06 = "KEY_UP"
0x1b = "KEY_RIGHT"
0x16 = "KEY_DOWN"
0x1a = "KEY_ENTER"
0x51 = "KEY_BACK"
0x55 = "KEY_PAGEUP"
0x15 = "KEY_PAGEDOWN"
0x46 = "KEY_PLAYPAUSE"
0x44 = "KEY_STOP"
0x18 = "KEY_HOMEPAGE"
0x58 = "KEY_PROGRAM"
0x08 = "KEY_PREVIOUS"
0x0b = "KEY_NEXT"
0x4a = "KEY_REWIND"
0x48 = "KEY_FASTFORWARD"
0x59 = "KEY_POWER"
0x45 = "KEY_MENU"
0x05 = "KEY_EXIT"
0x12 = "KEY_CONTEXT_MENU"
0x1f = "KEY_FAVORITES"
0x4  = "KEY_PVR"
0x4d = "KEY_EPG"
0x2  = "KEY_INFO"
0x9  = "KEY_SUBTITLE"
0x1  = "KEY_AUDIO"
0x0f = "KEY_NUMERIC_0"
0x52 = "KEY_NUMERIC_1"
0x50 = "KEY_NUMERIC_2"
0x10 = "KEY_NUMERIC_3"
0x56 = "KEY_NUMERIC_4"
0x54 = "KEY_NUMERIC_5"
0x14 = "KEY_NUMERIC_6"
0x4e = "KEY_NUMERIC_7"
0x4c = "KEY_NUMERIC_8"
0x0c = "KEY_NUMERIC_9"
