[[protocols]]
name = "VANDER"
protocol = "nec"
[protocols.scancodes]
0x108 = "KEY_MUTE"
0x114 = "KEY_VOLUMEDOWN"
0x110 = "KEY_VOLUMEUP"
0x106 = "KEY_HOME"
0x157 = "KEY_DVD"
0x147 = "KEY_LEFT"
0x146 = "KEY_UP"
0x115 = "KEY_RIGHT"
0x116 = "KEY_DOWN"
0x155 = "KEY_ENTER"
0x140 = "KEY_BACK"
0x13c = "KEY_PAGEUP"
0x14f = "KEY_PAGEDOWN"
0x11a = "KEY_PLAYPAUSE"
0x12b = "KEY_STOP"
0x141 = "KEY_HOMEPAGE"
0x14b = "KEY_PROGRAM"
0x118 = "KEY_POWER"
0x117 = "KEY_MENU"
0x156 = "KEY_CONTEXT_MENU"
0x15b = "KEY_FAVORITES"
0x104  = "KEY_INFO"
0x11f  = "KEY_AUDIO"
0x10c = "KEY_NUMERIC_0"
0x154 = "KEY_NUMERIC_1"
0x148 = "KEY_NUMERIC_2"
0x107 = "KEY_NUMERIC_3"
0x150 = "KEY_NUMERIC_4"
0x112 = "KEY_NUMERIC_5"
0x111 = "KEY_NUMERIC_6"
0x14c = "KEY_NUMERIC_7"
0x10e = "KEY_NUMERIC_8"
0x10d = "KEY_NUMERIC_9"
